#!/bin/bash

# Python version
PYTHON_VERSION_MAJOR=3
PYTHON_VERSION_MINOR=8
PYTHON_VERSION_MICRO=12
PYTHON_VERSION=${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}.${PYTHON_VERSION_MICRO}

# Python install directory
PYTHON_INSTALL_DIR=${HOME}/install/python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}${PYTHON_VERSION_MICRO}
